### ISSUE TITLE
render_thread

### ISSUE THREAD

**Issue by nikolja** [liblava/liblava#12]
Trying to code with liblava. Cool lib for fast prototyping. Can you show a little example how to use render_thread? Thank a lot.

**Comment by TheLavaBlock** [comment]
Sure. Currently `render_thread` is not used and just a prototype. 
I will add it to `app` next week as an example. Thanks

**Comment by nikolja** [comment]
I asked you about render_thread, because already started to think how to build a command buffers via multithreading in your nice designed liblava. I look at the code of liblava, there a lot of stuff designed safely. I found render_thread there and decide to ask your vision how to use it. Going to code more with liblava and will waiting for your solution with multithread render. Thank you for answer.

**Comment by TheLavaBlock** [comment]
Thanks for your patience. Unfortunately I had to do some other things this week, so I hope to post it next week. If you have suggestions for the `render_thread`, I'm of course open to them.

**Comment by nikolja** [comment]
> Thanks for your patience. Unfortunately I had to do some other things this week, so I hope to post it next week. If you have suggestions for the `render_thread`, I'm of course open to them.

Hi! Thank you for feedback again. I still did not tried to make something multithreaded with liblava. Waiting for your example and working on a helper to simplify the creation of vulkan pipeline layouts using liblava and SPIRV-Cross-reflection API. Going to share when it will be ready. Suggestions for the render_thread ? Multi threaded parallel command buffer generation, parallel per-frame recreation of secondary command buffers that are executed and submitted in a primary buffer once all threads have finished. Something like Hologramm sample from Vulkan SDK. Thank you!

**Comment by nikolja** [comment]
Hi! Thank you very much for update render_thread. Any examples or explaintation for using that? If you have a time ofcourse. Thanks.

**Comment by TheLavaBlock** [comment]
Sure. I'm still preparing the example implementation. Will let you know when I finish it.

**Comment by TheLavaBlock** [comment]
Unfortunately I have to remove the render thread because it is currently not in scope. 

I think in the future other methods will be interesting, like [Coroutines](https://en.cppreference.com/w/cpp/language/coroutines).
