### ISSUE TITLE
sRGB support

### ISSUE THREAD

**Issue by pezcode** [liblava/liblava#15]
Support for sRGB textures and swapchain would be nice to have. sRGB texture formats will perform the conversion to and from linear RGB in hardware. This is important for loading color images (this excludes normal maps, etc.) which are almost always stored as sRGB, as well as applying the correct gamma transformation for display output. You can do it manually, but that's slow, error prone and enforces bad habits.

Currently, three things are blocking this:

- Swapchain surface format doesn't request `_SRGB` formats, but `_UNORM`
- `load_texture` doesn't support `_SRGB` formats, even though all 4 formats (RGBA, BC, ASTC, ETC2) have SRGB versions. not sure why they're not supported, maybe there's a good reason I'm not aware of.
- Imgui :< theme colors are defined as sRGB, then interpolated in the shader (which is incorrect), and finally output as mangled sRGB. As a result, storing to an sRGB swapchain image will effectively apply the transform twice. There's an ongoing PR (https://github.com/ocornut/imgui/pull/2943) that partly fixes this. This is the real blocking thing here.

Would appreciate some input 😃 Maybe there's a reason you went without sRGB, or you think it's a non-issue.

**Comment by TheLavaBlock** [comment]
The first two issues should now be fixed. 

Request **sRGB** swapchain if needed:

```cpp
app.config.surface.formats = { VK_FORMAT_R8G8B8A8_SRGB };

if (!app.setup())
    return error::not_ready;
```

I don't know what to do about the last one (**imgui**) at the moment. Let's wait and see what happens there 👀

**Comment by TheLavaBlock** [comment]
**FYI:** Added FreeType in 89c95f2afb7a76045da461d2884d6f95b17377cb - See [Gamma Correct Blending](https://github.com/ocornut/imgui/tree/master/misc/freetype#gamma-correct-blending)

> FreeType assumes blending in linear space rather than gamma space. See FreeType note for FT_Render_Glyph. For correct results you need to be using sRGB and convert to linear space in the pixel shader output. The default Dear ImGui styles will be impacted by this change (alpha values will need tweaking).
