### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HorstBaerbel** [liblava/liblava#37]
There's no internal or API / usage documentation whatsoever. This hinders people using the library or contributing.
Ideally I'd use doxygen / Javadoc style comments for auto-generating documentation:
```
/// @brief Describe your class or function here.

/*
* \brief This works the same.
*/
```
I prefer the first version as it clutters up files less.

I also would enforce formatting using [clang-format](https://clang.llvm.org/docs/ClangFormat.html). It integrates nicely with VS-Code. Put a _.clang-format_ file into the root of the project and enable format on save in VS Code. You can then [adjust](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) the _.clang-format_ file to your needs and format code as you edit or let the CI check or format code for you as you commit.

**Comment by TheLavaBlock** [comment]
Sure. The documentation will be improved in the future. We already use clang-format in this project.

**Comment by TheLavaBlock** [comment]
Basic documentation. In the next step it will be corrected, improved and completed 🖊️
