### ISSUE TITLE
Can't load texture with mipmaps

### ISSUE THREAD

**Issue by pezcode** [liblava/liblava#4]
I'm using `load_texture` to load a .dds file with mipmaps but I'm getting the following validation error:

> vkCreateImage(): Image mip levels=11 exceed image format maxMipLevels=1 for format VK_FORMAT_R8G8B8A8_UNORM. The Vulkan spec states: mipLevels must be less than or equal to imageCreateMaxMipLevels (as defined in Image Creation Limits). (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageCreateInfo-mipLevels-02255)

It seems like `VK_IMAGE_TILING_LINEAR` doesn't support mipmaps on all hardware (at least not on my Nvidia GTX 1070). `texture::stage` seems to correctly transfer mipmaps from the scratch buffer, so I'm not sure why linear tiling is even necessary.

Commenting out the code that sets linear tiling removes the validation error, but I just wanted some feedback if that's valid, or why it's enabled by default.

**Comment by TheLavaBlock** [comment]
Yeah, you are right. No need to set tiling to `VK_IMAGE_TILING_LINEAR` in constructor of `texture`.
It should be `VK_IMAGE_TILING_OPTIMAL` per default, just like in `image.info`.

It's an incorrect default setting and that code line will be removed. Thank you.
