### ISSUE TITLE
First physical device is selected by default and there is no way to select another device

### ISSUE THREAD

**Issue by kureta** [liblava/liblava#5]
I have an Nvidia eGPU but Intel integrated GPU is listed as the first physical device. Since X is running on the eGPU, when I try to start a demo application I get the following warning:

```
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x360000b
  Serial number of failed request:  168
  Current serial number in output stream:  178
```

If I go inside `liblava/base/instance.hpp` line #64 and change `physical_devices.front()` to `physical_devices.back()` everything works as expected. But of course this is not a valid solution :)

**Comment by TheLavaBlock** [comment]
You're right. There are now several options:

**1. Set application default**
```cpp
app app("select");
app.config.physical_device = 1;

if (!app.setup())
    return error::not_ready;
```
**2. Select by command line**
```
$ lava -pd=1
$ lava --physical_device=1
```
**3. Change in _config.json_**
```
{
...
    "physical device": 1,
...
}
```

**Comment by kureta** [comment]
Wow! That was quick. Thanks!
