### ISSUE TITLE
Independent Project Build Fails - freetype not found

### ISSUE THREAD

**Issue by pyramid3d** [liblava/liblava#50]
When creating an independent project with the installed lava-install following the instructions from https://github.com/liblava/liblava/blob/master/DOCS.md/#build I do get this error:

```
CMake Error at CMakeLists.txt:2 (find_package):
  Found package configuration file:
    /data/projects/pyramid/lavatut/lib/cmake/lava/lava-config.cmake
  but it set lava_FOUND to FALSE so package "lava" is considered to be NOT
  FOUND.  Reason given by package:
  The following imported targets are referenced, but are missing: freetype
```

**Comment by TheLavaBlock** [comment]
Thanks for letting us know.
It looks like freetype is missing in the installation script. 
I'll have a closer look at it in a few days.

**Comment by TheLavaBlock** [comment]
Ok, let's keep things simple. It's already complicated as it is. 😉
