### ISSUE TITLE
Optional Dependencies

### ISSUE THREAD

**Issue by Cons-Cat** [liblava/liblava#60]
Every time I freshly clone Liblava, it takes a very long time, and that's not to mention waiting on clean-build times. A lot of the dependencies seem niche enough that I think they could / should be made optional. I don't think all users need a debug GUI every time, nor JSON. And I suspect most users might not want _Argh_ most of the time. I believe this friction could hamper broader adoption of Liblava.

Making these dependencies optional could also open the door to multiple backends. For example, using _DirectXMath_ instead of _GLM_. Or _SIMDJSON_ instead of _JSON For Modern C++_. This could be useful for larger projects that may want to integrate with other libraries that have redundant dependencies (especially if they want SDL2 instead of GLFW).

I'm thinking this might be achieved with a shell / batch script to handle project setup, and preprocessor #defines to handle conditional compilation. The CMake systems would probably also need to change somewhat.

**Comment by TheLavaBlock** [comment]
Well, liblava comes with these dependencies. There used to be even a few more, but they were removed 😉 

I would not like to introduce #defines and change that in CMake. If other developers want to use another library, they can do that without any problems and don't have to work with the one that is used. Also, this library is very modular, so you can leave some things out if you want. 

And if the cloning, which fortunately only has to be done once, takes a little longer, then I find that quite acceptable. 

We'll see how it behaves in the future. I'm still looking forward to C++ modules support in CMake, which I really hope would be a nice christmas present this year 🎁

**Comment by Cons-Cat** [comment]
Fair enough! This would be complicated to do and have a high maintenance cost. I think one day in the future it might want to be reconsidered, though.

> if other developers want to use another library (like DirectXMath or SIMDJSON), they can do that without any problems and don't have to work with the one that is used. 

That's not entirely without problems imo. For one, having redundant dependancies like GLM + DXMath or GLFW + SDL2 would significantly increase the binary size and compile times, which could be hard on game development.

There's also the possibility that somebody might have an existing DirectX11 project, and decide that the best way to support Vulkan would be Liblava rather than WineAPI. WineAPI is harder to debug than a thinner Vulkan abstraction, it's theoretically less portable, Idk. But then they might have issues casting between GLM and DXMath data, and the codebase becomes generally more complicated.

And GLFW vs SDL2 is a very fundamental decision that could be non-starter for some users. I think this would be the most important thing to consider supporting. At least having an option for not compiling ImGui, for instance in a release build, could also help a lot with the binary size and compile times in cases where it's only being used for debugging menus that can be excluded from release.
