### ISSUE TITLE
Latest release can not be built from Release downloads

### ISSUE THREAD

**Issue by danilw** [liblava/liblava#64]
https://github.com/liblava/liblava/releases/tag/0.6.2 download there Source code.

`liblava-0.6.2/ext` all folders are empty

`git submodule update --init --recursive` does not work because there no `.git` folder

building from `git clone` works

**Comment by TheLavaBlock** [comment]
Thanks for letting us know 👍

Here we go ➜ [liblava_2021_preview.zip](https://github.com/liblava/liblava/releases/download/0.6.2/liblava_2021_preview.zip)
