### ISSUE TITLE
Ability to select Vulkan version and extensions

### ISSUE THREAD

**Issue by pezcode** [liblava/liblava#7]
It would be nice if we could somehow pass a required Vulkan version (both instance and physical device) as well as required extensions (instance and device) to `app`.
The best place would probably be in `frame_config` since both frame and app have access to it.

**Comment by pezcode** [comment]
To add to that, maybe also device feature selection. This might be easier in a callback.

**Comment by TheLavaBlock** [comment]
Good idea. Now you can write for _example_:

```cpp
frame_config config;

config.app = "select version, layer and extension";
config.cmd_line = { argc, argv };

config.app_info.req_api_version = instance::api_version::v1_2;
config.param.layer_to_enable.push_back("VK_LAYER_LUNARG_api_dump");
config.param.extension_to_enable.push_back("VK_EXT_swapchain_colorspace");

app app(config);

if (!app.setup())
    return error::not_ready;
```

**Comment by pezcode** [comment]
That's great, thanks for the really fast change!

I thought you had to specify the device version in Vulkan too, but I just have to do this which works fine for me:
```c++
if(app.device->get_physical_device()->get_properties().apiVersion < VK_API_VERSION_1_1)
    return error::create_failed;
```

Any plans for enabling device extensions? (ie. some way to pass `device::create_param`) I wanted to experiment with the Nvidia raytracing extensions and even if it involves raw Vulkan code, the lava framework is really lovely to work with for prototyping.

**Comment by pezcode** [comment]
Maybe the easiest way to do this is to just check in `app.setup()` if `app.device` is already set and then skip creating a device. That way you can just use `device_manager`.

**Comment by TheLavaBlock** [comment]
Sounds good. Like this?

```cpp
app app(config);

auto param = instance::get_first_physical_device().create_default_device_param();

param.extensions.push_back("VK_KHR_device_group");

app.device = app.manager.create(param).get();

if (!app.setup())
    return error::not_ready;
```
Alternatively you can also do:

```cpp
app app(config);

app.manager.on_create_param = [](device::create_param& param) {

    param.extensions.push_back("VK_KHR_device_group");
};

if (!app.setup())
    return error::not_ready;
```

**Comment by TheLavaBlock** [comment]
At the moment all device features are supported which the physical device provides. 
This should be able to be changed if necessary.

**Comment by pezcode** [comment]
> Sounds good. Like this?

That's perfect. 👍 

> At the moment all device features are supported which the physical device provides.
> This should be able to be changed if necessary.

Yeah, feature selection is a little messy. For 1.0 features you can use `VkDeviceCreateInfo.pEnabledFeatures`. For extensions you need to use `VkDeviceCreateInfo.pNext`. Then for core features added in new versions of Vulkan, you have to use `VkPhysicalDeviceVulkan11Features`/`VkPhysicalDeviceVulkan12Features` in `pNext`. If you want to *query* extension/promoted features, you need to use `vkGetPhysicalDeviceFeatures2` and go through its `pNext` chain.

I think it's worth supporting, since extensions are widely used in Vulkan. The Lunarg docs [recommend not to enable all features](https://vulkan.lunarg.com/doc/view/1.0.37.0/linux/vkspec.chunked/ch31s01.html).

I'm not sure how to expose this nicely. An easy way out would be to have a `VkPhysicalDeviceFeatures` and a `p_next` member in `device::create_param` and add `physical_device::get_features2`. Maybe you have a better idea or you think it's too much effort. I don't want to mutilate your class interface 😅

**Comment by TheLavaBlock** [comment]
I already have an idea how to make it more practical, but that will take some time. 
Can you work with the current status?

**Comment by pezcode** [comment]
Works perfectly for me the way it is 👌 But I can understand if you want something a bit more clean.
I'd close the issue but maybe you want to leave it open for discussion, up to you.

Anyway, thanks for the fast fixes so far, much appreciated.

**Comment by TheLavaBlock** [comment]
Good call! #7 marks the next steps in this area. Let's leave it open. You're welcome!

**Comment by pezcode** [comment]
OoOo that's fancy 🤠
