### ISSUE TITLE
Outputting fps to a text file?

### ISSUE THREAD

**Issue by itzaeon** [liblava/liblava#76]
Hey, is there any method to outputting the fps that I get in say lava-lamp.exe into a text file? preferably through the command line / no user input needed.

**Comment by TheLavaBlock** [comment]
Hey 🖖, that sounds interesting. What do you think?

```
--fps {n} (default: 100)
```

* n - Number of frames

<br />

```
--fps_offset {n} (default: 0)
```

* n - Output offset

<br />

```
--fps_file {file} (default: fps.json)
```

* file - Output file

<br />

```
--fps_path {path} (default: pref_dir)
```

* path - Output path

**Comment by itzaeon** [comment]
Sounds great thank you!

**Comment by TheLavaBlock** [comment]
Nice, but that was just a suggestion how something like that could look like before it is implemented. 

Would you be satisfied with that? What would you actually use it for? 

You can reopen the issue if you want us to look into it further.

**Comment by itzaeon** [comment]
If possible, do you think you could log 0.1% FPS lows as wel?

**Comment by TheLavaBlock** [comment]
I was rather thinking of logging out the individual frame times (i.e. with a timestamp per frame). If you are interested in a certain thing, you can filter it out of the output data as needed.

**Comment by TheLavaBlock** [comment]
I have renamed the Command-Line Argument to reduce confusion, from `--fps` to `--frames`.

**Comment by TheLavaBlock** [comment]
The `json` format of the output file should be very easy to parse for now. Later on, more information can be added. 

If you want to go 'crazy', you could actually output the frames as images as well to analyze them. 
There might be much more possible in the future... 
I tend to use [RenderDoc](https://renderdoc.org/) for this, but it would be quite nice for benchmarking and automated workflows.

But first, let's take a closer look at the first use case. I think I'll come to it after the weekend.

💡 If anyone has any further suggestions and ideas, please feel free to add them here 😉

**Comment by TheLavaBlock** [comment]
Thanks for the reference to the other project 👍 

Unfortunately I didn't make it this week and have other things to do. But I'll keep an eye on it... 👀

**Comment by TheLavaBlock** [comment]
Finally [Guide/Benchmark](https://github.com/liblava/liblava/blob/master/doc/Guide.md#benchmark) :balloon: 

Hope that's enough for now. Feedback is welcome. Feel free to open a new issue. Have fun with it! :wink:
