### ISSUE TITLE
PresentMon-like frametime logging

### ISSUE THREAD

**Issue by amitxv** [liblava/liblava#77]
This has been previously requested however, i would like to suggest implementing PresentMon frametime logging to a csv log so that it can be used universally & analysed in popular tools such as CapframeX.

**Comment by TheLavaBlock** [comment]
Thanks for the suggestion. Can be quite useful for the feature in #76 
👍

**Comment by TheLavaBlock** [comment]
Hey, **liblava** supports now benchmarks: #76 - see [Guide/Benchmark](https://github.com/liblava/liblava/blob/master/doc/Guide.md#benchmark) :balloon: 

Check it out when you have time :eyes: 

I wouldn't export anything other than the `json` file. It should actually be fairly easy to transform it for other purposes.
