### ISSUE TITLE
Does cmake ver need to be that high? Raspberry OS on 3.18

### ISSUE THREAD

**Issue by Fredrum** [liblava/liblava#88]
Hello!

Am going to try your Vulkan framework here hoping that it will offer a more sane programming experience than having to do it all from scratch.

Im working on a Raspberry Pi 4b with latest OS and stumble on the very first hurdle, 

```
CMake Error at CMakeLists.txt:5 (cmake_minimum_required):
  CMake 3.22 or higher is required.  You are running version 3.18.4
```

I'll have to figure out how to get a higher version but just wanted to ask if 3.22 is really essential?

Cheers!

**Comment by TheLavaBlock** [comment]
Hi :wave:

The easiest way is to downgrade the version in your local `CMakeLists.txt` - everything should work.

Raspberry Pi  :eyes:  Excellent, I also tried it a while ago: #39

`lava` flows on current versions to keep updates small and timely.

I hope the framework helps you :wink:

**Comment by Fredrum** [comment]
Ha ok that sounds good!
I'm just building cmake from source and its a quite long process so once that's finished I'll try your suggestion instead!

I'm excited to test this out! :)

**Comment by TheLavaBlock** [comment]
:+1: Great that we could clarify this. 

If you have feedback, get in touch...
I'd be interested to know how `lava` is currently running on the Pi.

I'll close this for now.

**Comment by Fredrum** [comment]
I installed some stuff needed and then cmake was able to run quite far but just got this error,
(using cmake 3.18)

```
CMake Error at CMakeLists.txt:509 (cmake_path):
  Unknown CMake command "cmake_path".
```

**Comment by TheLavaBlock** [comment]
Ahh yeah, sorry, this requires CMake 3.20
