### ISSUE TITLE
How do I set up a cmake project?

### ISSUE THREAD

**Issue by Fredrum** [liblava/liblava#89]
Hello!

Iv'e managed to build liblava on my Raspberry Pi4b, Raspberry OS Bullseye! :)
Some examples worked others didn't but that's good enough for me!

So now I'm trying to set up a external (to liblava) project to start making some simple programs following your tutorial code.

But I'm getting a bunch of errors for not finding various include files. How should I set this up with cmake so that I don't need to add all those paths one by one and by hand?

I saw in an older 'Issue' there were some suggestions but the links were broken,

https://github.com/liblava/liblava/blob/master/DOCS.md/#install
https://github.com/liblava/liblava-template

Cheers!

**Comment by Fredrum** [comment]
Wait ok found and followed these instructions
https://github.com/liblava/liblava#install

and managed to build the first simple 'frame' code,
```
#include <liblava/lava.hpp>
using namespace lava;

int main(int argc, char* argv[]) {
    lava::frame frame( {argc, argv} );
    return frame.ready() ? 0 : error::not_ready;
}
```

I guess I should expect to see a window?
But no window shows up and I get this message,

`WARNING: v3dv is neither a complete nor a conformant Vulkan implementation. Testing use only.`

**Comment by TheLavaBlock** [comment]
Hey,

**frame** itself doesn't handle windows, that's what the layer above it does: **app**

In the tutorial is an example how to create a simple window.

**Comment by TheLavaBlock** [comment]
I'm closing this again. If you get stuck, you can join the [discord](https://discord.lava-block.com/) server or leave a comment here.
