### ISSUE TITLE
How to insert render passes before gui?

### ISSUE THREAD

**Issue by pezcode** [liblava/liblava#9]
What is the best way to do this? My plan is to render everything to an offscreen framebuffer (deferred shading + possibly tonemapping) and then just perform a final blit to the render target before the gui pipeline.

I could call `block.add_cmd()` before `app.setup()` but that creates a new command buffer. Would that be a problem, performance wise? And can I still insert barriers properly even if they cross command buffers? Bit of a Vulkan newbie so I could use some input 😄

**Comment by TheLavaBlock** [comment]
If you **don't** want to create a new command buffer, you can write now:
```cpp
app.on_process = [&](VkCommandBuffer cmd_buf, index frame) {

    ...
};
```

There are several ways to implement in Vulkan. So, what's best is hard to say. Best would be to test and measure performance on some systems. As this framework is for prototyping and education purpose, I hope it can be of some help to you.

That is interesting to note:
https://devblogs.nvidia.com/vulkan-dos-donts/

**Comment by pezcode** [comment]
Oooo that's perfect, thank you!

I'll have to do some experimenting once I get it roughly working. Vulkan can be very overwhelming because there are so many ways to do things. Appreciate the link, some really good info in there 👍
