### ISSUE TITLE
Add support to supply semaphores to renderer

### ISSUE THREAD

**Issue by daniel-keitel** [liblava/liblava#95]
Awesome project.
Currently there is no way (I found) to add synchronization between own command buffers and the main one used by the renderer.
This becomes a big issue when working with multiple command queues.
It would be great to be able to inject additional wait and signal semaphores to allow for synchronization.

**Comment by TheLavaBlock** [comment]
Welcome!

Thanks for your feedback and your PR. I'm glad you like it.

Right now I'm busy and would like to take some more time for your request here as well. I also found your project, which looks very interesting.

I think I come on the weekend to take a closer look in there. Maybe someone else will also check it out and give feedback.
