### ISSUE TITLE
Unable to take screenshots (how to best extend create methods)

### ISSUE THREAD

**Issue by daniel-keitel** [liblava/liblava#98]
When trying to take a screenshot I receive the following validation error:
```
[2023-02-15 20:12:12.381] [lava] [error] validation: VUID-vkMapMemory-memory-00682 (-330527817)
[2023-02-15 20:12:12.382] [lava] [error] Validation Error: [ VUID-vkMapMemory-memory-00682 ] Object 0: handle = 0x535b66
0000000043, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xec4c8bb7 | Mapping Memory without VK_MEMORY_PROPERTY_HO
ST_VISIBLE_BIT set: VkDeviceMemory 0x535b660000000043[]. The Vulkan spec states: memory must have been created with a me
mory type that reports VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT (https://vulkan.lunarg.com/doc/view/1.3.231.1/windows/1.3-ext
ensions/vkspec.html#VUID-vkMapMemory-memory-00682)
Assertion failed: !"check validation error", file C:\Users\daniel\CLionProjects\fluid_bending\ext\liblava_fork\liblava\b
ase\instance.cpp, line 36
```

The issue seams to be that `VMA_MEMORY_USAGE_AUTO_PREFER_HOST` doesn't guarantee that the memory is host visible, 
so mapping it fails.

[VmaMemoryUsage](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#gaa5846affa1e9da3800e3e78fae2305cc)

Changing it to `VMA_MEMORY_USAGE_CPU_TO_GPU` would fix it, but it is deprecated.

To properly solve this issue : [VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#ggad9889c10c798b040d59c92f257cae597a9be224df3bfc1cfa06203aed689a30c5) or [VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#ggad9889c10c798b040d59c92f257cae597add61238d98e20917b9a06c617763f492) would be required in the allocation flags.

To implement this the create method of image would require a new parameter to set the allocation flag.

Here I see a general problem with liblava's create methods. They are a nice abstraction to create complex objects like buffers, meshes and images, but they severely limit how they can be created.
Examples: 
- allocation info for images 
- 3d textures
- creation of meshes accessible in compute shades

I see no clear way to fix this problem, but some options are:
- (make members required for creation public (bad hack))
- (add way more parameters to creation methods (bloats methods)
- add additional create method accepting a function, with accepts references to all required members for creation. (complicated for the user, but simple to implement)
- add create_info struct as parameter
- add methods to change default creation parameters

The last two would be the best options in my opinion.

Maybe this should be discussed in a separate issue.

**Comment by TheLavaBlock** [comment]
Thanks for your report. I will take a closer look at the problem.

**Comment by TheLavaBlock** [comment]
You're right, we could make the allocation more accessible to the user. VMA has become the standard and offers a good abstraction. In the long run it makes sense to make this more available to the user. We might make further adjustments to this, but for now the screenshot problem should be solved this way. 

Thanks again for your feedback and the suggestion for the fix. I appreciate it very much.
